### ISSUE TITLE
characters method is assumed to be called only once

### ISSUE THREAD

**Issue by duursma** [bjornharrtell/jts-topo-suite#2]
I have tried to use this example to read an kml file. It turns out that for big files it breaks the text in one of the elements.  This is caused by the characters handler to be called multiple times for a single element.  This seems to be the correct behavior and characters should be collected until the endElement

**Comment by bjornharrtell** [comment]
Your text makes no sense to me and this is just an experimental fork of an upstream project. Will delete now.
